---
name: manylinux

on:
  pull_request:
    branches: [main]
    paths:
      - 'docker-bake.manylinux.hcl'
      - 'Dockerfile.manylinux*'
      - 'scripts/**'

permissions: {}

jobs:
  bake:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            targets: x86_64,x86_64-plugins
            host_runner: ubuntu-latest
          - arch: aarch64
            targets: aarch64,aarch64-plugins
            host_runner: ubuntu-24.04-arm

    name: manylinux_2_28 (${{ matrix.arch }})
    runs-on: ${{ matrix.host_runner }}

    steps:
      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake and Push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.manylinux.hcl
          targets: ${{ matrix.targets }}
